# -*- coding: utf-8 -*-

import argparse
from copy import deepcopy
import os
from pathlib import Path
import sys

from scrapy.crawler import CrawlerProcess
from scrapy.utils.project import get_project_settings


def generate_settings(base_dir, base_settings, start_time):

    settings = deepcopy(base_settings)

    blog_dir = base_dir / 'blogs'
    latest_dir = blog_dir / 'LATEST'
    daily_dir = blog_dir / start_time

    if not latest_dir.exists():
        latest_dir.mkdir(parents=True)
    if not daily_dir.exists():
        daily_dir.mkdir()

    settings['IMAGES_STORE'] = str(base_dir/'images')
    settings['LATEST_DIR_POINTER'] = str(latest_dir/'latest.txt')
    settings['DAILY_DIR'] = str(daily_dir)
    settings['BLOG_TEMPLATE'] = '{blog}.csv'

    settings['LOG_LEVEL'] = 'WARNING'
    settings['LOG_FILE'] = str(daily_dir/'log.txt')

    return settings


if __name__ == '__main__':
    src_path = str(Path(__file__).resolve().parents[1])
    sys.path.insert(0, src_path)

    from blog_scraper.spiders.blogs import BlogsSpider
    # Config ArgumentParser
    parser = argparse.ArgumentParser(description='Parse curation blogs.')
    parser.add_argument('-d', default='.', type=str, required=False,
                        dest='base_dir',
                        help='Base directory for files generated by spiders')
    parser.add_argument('-t', type=str, required=True, dest='start_time',
                        help='When the task is started, used for folder names')

    # Parse arguments
    args = parser.parse_args()
    base_dir = Path(args.base_dir)
    start_time = args.start_time

    # Set BASE_DIR environment variable for utils.urlutil
    os.environ['SCRAPER_CONFIG_DIR'] = str(base_dir/'corvid_config')

    # Retrieve the settings from `settings.py` file
    os.environ['SCRAPY_SETTINGS_MODULE'] = 'blog_scraper.settings'
    base_settings = get_project_settings()

    settings = generate_settings(base_dir, base_settings, start_time)
    process = CrawlerProcess(settings)
    process.crawl(BlogsSpider)
    process.start()
